apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap-node1-5
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Asia/Kolkata"
  SERVERPORT: "31829"
  PEERS: "2"
  ALLOWEDIPS: "0.0.0.0/0, ::/0"
  INTERNAL_SUBNET: "20.1.2.0"

---
apiVersion: v1
kind: Pod
metadata:
  name: wireguard-node1-5
  annotations:
    contivpp.io/custom-if: eth1/tap/stub, eth2/tap/stub
  labels:
    cnf: wireguard-node1-5
    app: wireguard-node1-5
spec:
  containers:
  - name: wireguard-node1-5
    #    image: linuxserver/wireguard
    image: 836891784212.dkr.ecr.us-east-1.amazonaws.com/wireguard:v3.0
    envFrom:
    - configMapRef:
        name: wireguard-configmap-node1-5
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - SYS_MODULE
      privileged: true
    ports:
    - containerPort: 51829
      protocol: UDP
      #    resources:
      #  requests:
      #   memory: "64Mi"
      #  cpu: "100m"
      # limits:
      # memory: "128Mi"
      # cpu: "200m"
  nodeSelector:
    disktype: chain1
  imagePullSecrets:
    - name: regcred
  dnsConfig:
    nameservers:
      - 8.8.8.8
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: wireguard-node1-5
  name: wireguard-service-node1-5
spec:
  type: NodePort
  ports:
  - port: 51829
    nodePort: 31829
    protocol: UDP
    targetPort: 51829
  selector:
    app: wireguard-node1-5

