---
apiVersion: contivpp.io/v1
kind: ServiceFunctionChain
metadata:
  name: linux-3-chain2
spec:
  chain:
    - name: CNF 1
      type: Pod
      podSelector:
        cnf: wireguard-node1-2
      interface: eth2

    - name: CNF 2
      type: Pod
      podSelector:
        cnf: vcr-node1-2
      interface: eth1
  nodeSelector:
    disktype: chain1
