---
apiVersion: contivpp.io/v1
kind: ServiceFunctionChain
metadata:
  name: linux-1-chain1
spec:
  chain:
    - name: CNF 1
      type: Pod
      podSelector:
        cnf: wireguard-node1-1
      interface: eth2

    - name: CNF 2
      type: Pod
      podSelector:
        cnf: vcr-node1-1
      interface: eth1
  nodeSelector:
    disktype: chain1
